# 🌦️ Weather Trend Forecasting

## PM Accelerator Technical Assessment

### Objective
The objective of this project is to analyze the **Global Weather Repository** dataset and forecast future weather trends using Machine Learning and Time Series Analysis.

This project covers:

- Data Cleaning & Preprocessing
- Exploratory Data Analysis (EDA)
- Time Series Forecasting
- Model Evaluation
- Insights and Conclusions

---

**Dataset**

Global Weather Repository (Daily Updating)

The dataset contains daily weather observations from cities around the world, including over 40 weather-related features such as:

- Temperature
- Humidity
- Wind Speed
- Pressure
- Visibility
- Air Quality
- Precipitation

The dataset is updated daily and is suitable for weather forecasting and climate trend analysis.

---

# Importing Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [5]:
df = pd.read_csv('Dataset/GlobalWeatherRepository.csv')

In [6]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [7]:
df.shape

(149880, 41)

In [8]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149880 entries, 0 to 149879
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       149880 non-null  object
 1   location_name                 149880 non-null  object
 2   latitude                      149880 non-null  float64
 3   longitude                     149880 non-null  float64
 4   timezone                      149880 non-null  object
 5   last_updated_epoch            149880 non-null  int64
 6   last_updated                  149880 non-null  object
 7   temperature_celsius           149880 non-null  float64
 8   temperature_fahrenheit        149880 non-null  float64
 9   condition_text                149880 non-null  object
 10  wind_mph                      149880 non-null  float64
 11  wind_kph                      149880 non-null  float64
 12  wind_degree                   149880 non-null  int64
 13  wind_direction                149880 non-null  object
 14  pressure_mb                   149880 non-null  float64
 15  pressure_in                   149880 non-null  float64
 16  precip_mm                     149880 non-null  float64
 17  precip_in                     149880 non-null  float64
 18  humidity                      149880 non-null  int64
 19  cloud                         149880 non-null  int64
 20  feels_like_celsius            149880 non-null  float64
 21  feels_like_fahrenheit         149880 non-null  float64
 22  visibility_km                 149880 non-null  float64
 23  visibility_miles              149880 non-null  float64
 24  uv_index                      149880 non-null  float64
 25  gust_mph                      149880 non-null  float64
 26  gust_kph                      149880 non-null  float64
 27  air_quality_Carbon_Monoxide   149880 non-null  float64
 28  air_quality_Ozone             149880 non-null  float64
 29  air_quality_Nitrogen_dioxide  149880 non-null  float64
 30  air_quality_Sulphur_dioxide   149880 non-null  float64
 31  air_quality_PM2.5             149880 non-null  float64
 32  air_quality_PM10              149880 non-null  float64
 33  air_quality_us-epa-index      149880 non-null  int64
 34  air_quality_gb-defra-index    149880 non-null  int64
 35  sunrise                       149880 non-null  object
 36  sunset                        149880 non-null  object
 37  moonrise                      149880 non-null  object
 38  moonset                       149880 non-null  object
 39  moon_phase                    149880 non-null  object
 40  moon_illumination             149880 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 46.9+ MB

In [10]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,149880.000000,149880.000000,1.498800e+05,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,...,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000,149880.000000
mean,19.233784,21.899291,1.749207e+09,21.313501,70.366088,7.947467,12.793991,169.308467,1014.064578,29.944745,...,18.106679,439.581153,57.643549,14.544581,9.949382,23.496847,47.150311,1.674099,2.547378,49.870677
std,24.403834,65.779640,1.925660e+07,9.532220,17.157850,7.035507,11.319112,103.533455,10.021209,0.295873,...,13.564333,730.098409,30.620229,22.991407,34.119027,35.730912,145.301421,0.927524,2.404225,35.023184
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,4.050300,-6.836100,1.732611e+09,16.000000,60.800000,3.800000,6.100000,80.000000,1010.000000,29.830000,...,10.100000,188.700000,38.000000,1.750000,1.110000,6.950000,9.750000,1.000000,1.000000,15.000000
50%,17.250000,23.236100,1.749200e+09,23.600000,74.600000,6.700000,10.800000,162.000000,1014.000000,29.930000,...,15.200000,281.200000,54.400000,5.650000,2.405000,13.690000,19.250000,1.000000,2.000000,50.000000
75%,40.400000,49.882200,1.765784e+09,27.900000,82.200000,11.000000,17.600000,256.000000,1018.000000,30.060000,...,24.000000,442.150000,73.000000,16.650000,7.950000,26.850000,40.330000,2.000000,3.000000,85.000000
max,65.300000,179.220000,1.782540e+09,79.300000,174.700000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

# Handling Missing Value

In [13]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [15]:
df = df.dropna()

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.shape

(149880, 41)

In [19]:
df['last_updated'] = pd.to_datetime(df['last_updated'])
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [20]:
df["last_updated"] = pd.to_datetime(df["last_updated"])

In [21]:
df["year"] = df["last_updated"].dt.year
df["month"] = df["last_updated"].dt.month
df["day"] = df["last_updated"].dt.day
df["dayofweek"] = df["last_updated"].dt.dayofweek
df["dayofyear"] = df["last_updated"].dt.dayofyear

In [24]:
final_df = df
final_df.to_csv("Dataset/cleaned_dataset.csv", index=False)